.\"
.\"  6tunnel v0.10
.\"  (C) Copyright 2000-2003 by Wojtek Kaniewski <wojtekka@bydg.pdi.net>
.\"
.TH 6TUNNEL 1 "Apr 14, 2003"
.SH NAME
6tunnel \- tunnelling for application that don't speak IPv6
.SH SYNOPSIS
.B 6tunnel
[
.B \-146dhfv
] [
.BI \-u
.IR username
] [
.BI \-i
.IR password
] [
.BI \-I
.IR password
] [
.BI \-l
.IR local\_host
] [
.BI \-L
.IR limit
] [
.BI \-m
.IR map\_file
]
] [
.BI \-p
.IR pid\_file
]
.IR local\_port
.IR remote\_host
[
.IR remote\_port
]
.SH DESCRIPTION
.B 6tunnel
allows you to use services provided by IPv6 hosts with IPv4-only
applications and vice-versa. It can bind to any of your IPv4 (default) or
IPv6 addresses and forward all data to IPv4 or IPv6 (default) host. For
example
.IP
.BI 6tunnel "\ " \-1 "\ " 6668 "\ " irc6.net "\ " 6667
.LP
will be enough to connect to IPv6 irc server with
.IP
.BI irc "\ " foobar "\ " localhost:6668
.LP
If you don't wish to run
.B 6tunnel
every time you want to show your :c001: or :dead: IPv6 address on IRC,
you can use
.B \-i
parameter, which makes
.B 6tunnel
ask your client for specified password. Just run
.IP
.BI 6tunnel "\ " \-i "\ " dupa.8 "\ " 31337 "\ " irc6.net "\ " 6667
.LP
and then type
.IP
.BI irc "\ " foobar "\ " localhost:31337:dupa.8
.LP
If your IRC server requires you to send password, specify it with
.B \-I
parameter -- after successful proxy authentication
.B 6tunnel
will send it to the server.

.B 6tunnel
can also be used as a tunnel for all other combinations of IPv4 and IPv6
endpoints. If remote host doesn't have any IPv6 addresses,
.B 6tunnel
will use the IPv4 one. In other cases, use
.B \-4
parameter which makes IPv4 address the preffered one. For IPv6-to-any tunnels
use
.B \-6
which makes
.B 6tunnel
bind to IPv6 address.
.SH OPTIONS
.TP
.B \-1
Exit after first connection.
.TP
.B \-4
Preffer IPv4 endpoint if the machine has both address types.
.TP
.B \-6
Listen on IPv6 address (IPv4 is default).
.TP
.B \-d
Don't detach.
.TP
.B \-f
Force tunneling even if remote host is not resolvable at the execution time.
.TP
.B \-h
Print hex dump of every packet received or sent (hu-huh, Beavis, he said
hex dump!)
.TP
.BI \-u "\ " username
Change UID and GID after bind().
.TP
.BI \-i "\ " password
Act as an IRC proxy and require user to authenticate.
.TP
.BI \-I "\ " password
If you are using
.B 6tunnel
as an IRC proxy and the IRC server requires you to send password, place
it right here.
.TP
.BI \-l "\ " local_host
Listen on specified address (IPv4, or IPv6 if
.B \-6
used).
.TP
.BI \-L "\ " limit
Limit simultaneous connections.
.TP
.BI \-m "\ " map_file
Bind to different IPv6 addresses, depending on client's IPv4 address.
Example file format:
.IP
.nf
.ta +3i
127.0.0.1 3ffe:8010:7::3
192.168.16.2 3ffe:8010:7::5
.fi
.IP
With this option specified connections will be allowed only from
listed hosts. To allow any host to connect you have to add mapping 
for 0.0.0.0 address.
.TP
.BI \-p "\ " pid_file
Write down pid to specified file.
.TP
.BI \-s "\ " source_host
Connect to the remote host using specified source address.
.TP
.B \-v
Be verbose and don't detach.
.SH THANKS
#ipv6 crew, Lam.
.SH BUGS
Terrible man page. Hex dump doesn't include IRC proxy authentication.
IRC proxy requires your client to send password first (don't worry ircii,
EPIC, BitchX, mIRC and many more will work). No logging except debug output.
.SH AUTHORS
Wojtek Kaniewski (wojtekka@bydg.pdi.net),
Tomek Lipski (lemur@irc.pl),
Dariusz Jackowski (ascent@linux.pl)
.SH "SEE ALSO"
.BR ssh (1)
